# Generated by Django 5.0.1 on 2024-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp1', '0002_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, null=True)),
                ('room_type', models.CharField(max_length=50, null=True)),
                ('room_price', models.CharField(max_length=50, null=True)),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
    ]
