# Generated by Django 5.0.1 on 2024-02-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp1', '0003_roomtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkindate', models.DateField()),
                ('checkoutdate', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp1.guesttable')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp1.roomtable')),
            ],
        ),
    ]
